services:
  - type: web
    name: beahead
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://hsckgramsgokjtvcymhv.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_a9BOUjYmfa2XId79ma_x9Q_xRksM9TZ
